/*
 * File: app/model/Contaminante.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RespiraXixon.model.Contaminante', {
    extend: 'Ext.data.Model',

    config: {
        idProperty: '',
        fields: [
            {
                name: 'estacion'
            },
            {
                name: 'titulo'
            },
            {
                name: 'latitud'
            },
            {
                name: 'longitud'
            },
            {
                name: 'fechasolar_utc_'
            },
            {
                name: 'so2'
            },
            {
                name: 'no'
            },
            {
                name: 'co',
                type: 'string'
            },
            {
                name: 'pm10'
            },
            {
                name: 'o3'
            },
            {
                name: 'dd'
            },
            {
                name: 'vv'
            },
            {
                name: 'tmp'
            },
            {
                name: 'hr'
            },
            {
                name: 'prb'
            },
            {
                name: 'rs'
            },
            {
                name: 'll'
            },
            {
                name: 'ben'
            },
            {
                name: 'tol'
            },
            {
                name: 'mxil'
            },
            {
                name: 'pm25'
            }
        ]
    }
});