/*
 * File: app/model/Contaminante.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RespiraXixon.model.Detalle_Estacion', {
    extend: 'Ext.data.Model',

    config: {
        idProperty: '',
        fields: [
            {
                name: 'estacion'
            },
            {
                name: 'titulo'
            },
            {
                name: 'latitud'
            },
            {
                name: 'longitud'
            },
            {
                name: 'fechasolar_utc_'
            },
            {
                name: 'so2'
            },
            {
                name: 'no'
            },
            {
                name: 'co'
            },
            {
                name: 'pm10'
            },
            {
                name: 'o3'
            },
            {
                name: 'dd'
            },
            {
                name: 'vv'
            },
            {
                name: 'tmp'
            },
            {
                name: 'hr'
            },
            {
                name: 'prb'
            },
            {
                name: 'rs'
            },
            {
                name: 'll'
            },
            {
                name: 'ben'
            },
            {
                name: 'tol'
            },
            {
                name: 'mxil'
            },
            {
                name: 'pm25'
            },
            {
                name: 'co_med_8'
            },
            {
                name: 'co_med_24'
            },
            {
                name: 'so2_med_8'
            },
            {
                name: 'so2_med_24'
            },
            {
                name: 'pm10_med_8'
            },
            {
                name: 'pm10_med_24'
            },
            {
                name: 'no_med_8'
            },
            {
                name: 'no_med_24'
            },
            {
                name: 'o3_med_8'
            },
            {
                name: 'o3_med_24'
            },
            {
                name: 'ind_global_rx_ayt_gijon',
                 type: 'int'
            },
            {
                name: 'ind_global_rx_legal',
                 type: 'int'
            },
            {
                name: 'ind_global_rx_oms',
                 type: 'int'
            }
        ]
    }
});