/*
 * File: app/store/Contaminantes.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RespiraXixon.store.Contaminantes', {
    extend: 'Ext.data.Store',

    requires: [
        'RespiraXixon.model.Contaminante'
    ],

    config: {
        model: 'RespiraXixon.model.Contaminante',
        storeId: 'Contaminantes',
        proxy: {
            type: 'ajax',
            url: 'datos/calidadaire.json',
            reader: {
                type: 'json',
                rootProperty: 'calidadairemediatemporales.calidadairemediatemporal'
            }
        }
    }
});