/*
 * File: app/view/FicherosTabPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RespiraXixon.view.FicherosTabPanel', {
    extend: 'Ext.tab.Panel',
	xtype : 'ficherostabpanel',
	requires: ['RespiraXixon.store.Estaciones','RespiraXixon.store.Indices','RespiraXixon.store.Contaminantes'],
    config: {
        items: [
            {
                xtype: 'container',
                autoLoad: true,
                title: 'Estaciones',
                ui: '',
                layout: {
                    type: 'card'
                },
                scrollable: true,
                items: [
                    {
                        xtype: 'list',
                        autoLoad: true,
                        itemTpl: [
                            '<div>Estacion: {id} - {titulo}</div>',
                            '<div>Direccion: {direccion}, {poblacion}, {provincia}</div>',
                            '<div>Coordenadas: {latitud} - {longitud}</div>'
                        ],
                        store: 'Estaciones'
                    },
                    {
                        xtype: 'panel'
                    }
                ]
            },
            {
                xtype: 'container',
                autoLoad: true,
                title: 'Contaminantes',
                ui: '',
                layout: {
                    type: 'card'
                },
                items: [
                    {
                        xtype: 'list',
                        autoLoad: true,
                        ui: 'round',
                        itemTpl: [
                            '<div>Estacion: {estacion} - {titulo}</div>',
                            '<div>Coordenadas: {latitud} - {longitud}</div>',
                            '<div>Co: {co} Pm10:{pm10} So2:{so2} No:{no} O3:{o3}</div>'
                        ],
                        store: 'Contaminantes'
                    }
                ]
            },
            {
                xtype: 'container',
                autoLoad: true,
                title: 'Indices',
                ui: '',
                layout: {
                    type: 'card'
                },
                items: [
                    {
                        xtype: 'list',
                        autoLoad: true,
                        ui: 'round',
                        itemTpl: [
                            '<div>Organizacion: {organizacion}</div>',
                            '<div>Contaminante: {contaminante}</div>',
                            '<div>Indice: {indice}</div>',
                            '<div>Calidad: {calidad}</div>',
                            '    '
                        ],
                        store: 'Indices'
                    }
                ]
            }
        ]
    }

});