/*
 * File: app/view/FicherosTabPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RespiraXixon.view.GraficasTabPanel', {
    extend: 'Ext.tab.Panel',
	xtype : 'graficastabpanel',
	requires: ['RespiraXixon.store.Contaminantes',"Ext.ux.RXUtils"],
    config: {
        items: [
            {
                xtype: 'container',
                title: 'Gráficas',
                ui: '',
                layout: {
                    type: 'card'
                },
                scrollable: true,
                items: [
                /*
                    {
                        xtype: 'list',
                        autoLoad: true,
                        itemTpl: [
                            '<div>Estacion: {id} - {titulo}</div>',
                            '<div>Direccion: {direccion}, {poblacion}, {provincia}</div>',
                            '<div>Coordenadas: {latitud} - {longitud}</div>'
                        ],
                        store: 'Estaciones'
                    }*/
                ]
            },
            {
                xtype: 'container',
                title: 'Datos',
                ui: '',
                layout: {
                    type: 'card'
                },
                items: [
                    {
                        xtype: 'list',
                        id:"lista",
                        ui: 'round',
                        itemTpl: [
                            '<div>Organizacion: {organizacion}</div>'/*,
                            '<div>Contaminante: {contaminante}</div>',
                            '<div>Indice: {indice}</div>',
                            '<div>Calidad: {calidad}</div>',
                            '    '*/
                        ]                    
                	}
                ]
            }
        ]
    },
	initialize: function()
	{
		console.log("Activa");
		var lista=Ext.getCmp("lista");
		console.log(Ext.getStore("Detalle_estaciones"));
		lista.setStore("Detalle_Estaciones");
		lista.refresh();
		this.callParent(arguments);
	}
});