/*
 * File: app/view/InicioTabPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RespiraXixon.view.InicioTabPanel', {
    extend: 'Ext.tab.Panel',
    requires: ['Ext.ux.OpenLayersMap','RespiraXixon.view.FicherosTabPanel','RespiraXixon.view.GraficasTabPanel',"Ext.ux.RXUtils"],
	
    config: {
        tabBar: {
            docked: 'bottom'
        },	
        items: [
            {
                xtype:'panel',
                title: 'Mapa',
                iconCls: 'maps',
                layout: 'fit',
                id: 'iniciotab',
                itemId: 'InicioTab',
                layoutOnTabChange: true,
                items: [
                        {
                            // Ext.ux.OpenLayersMap Component
                            xtype: 'openlayersmap',
                            id: 'openlayersmap',
                            useCurrentLocation: false,
                            autoMapCenter: false,
                            mapOptions: {
                                zoom: 13,
                                center: {longitude:-5.6626443, latitude:43.5450394},
                                theme: 'src/Openlayers/theme/default/style.mobile.css'
                        	}
                        }
             		]
            },
            {
                xtype: 'container',
                title: 'Ficheros',
                layout: 'fit',
                iconCls: 'info',
                items:[
	                {
	                    xtype: 'ficherostabpanel'
	                }
	            
                ]
            },
            {
                xtype: 'container',
                title: 'Gráficas',
                layout: 'fit',
                iconCls: 'favorites',
                items:[
	                {
	                    xtype: 'graficastabpanel'
	                }
	            
                ]
            }
        ]
    }
});